//
// Generated file, do not edit! Created by nedtool 5.4 from simpleMsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __SIMPLEMSG_M_H
#define __SIMPLEMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include <vector>
typedef std::vector<int> IntVector;
// }}

/**
 * Class generated from <tt>simpleMsg.msg:23</tt> by nedtool.
 * <pre>
 * message simpleMsg
 * {
 *     double amount;
 *     double timeSent;  //time after start time that job is active
 *     int sender;
 *     int receiver;
 *     IntVector route;
 *     int priorityClass;
 *     int hopCount = 0;
 * 
 * }
 * </pre>
 */
class simpleMsg : public ::omnetpp::cMessage
{
  protected:
    double amount;
    double timeSent;
    int sender;
    int receiver;
    IntVector route;
    int priorityClass;
    int hopCount;

  private:
    void copy(const simpleMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const simpleMsg&);

  public:
    simpleMsg(const char *name=nullptr, short kind=0);
    simpleMsg(const simpleMsg& other);
    virtual ~simpleMsg();
    simpleMsg& operator=(const simpleMsg& other);
    virtual simpleMsg *dup() const override {return new simpleMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getAmount() const;
    virtual void setAmount(double amount);
    virtual double getTimeSent() const;
    virtual void setTimeSent(double timeSent);
    virtual int getSender() const;
    virtual void setSender(int sender);
    virtual int getReceiver() const;
    virtual void setReceiver(int receiver);
    virtual IntVector& getRoute();
    virtual const IntVector& getRoute() const {return const_cast<simpleMsg*>(this)->getRoute();}
    virtual void setRoute(const IntVector& route);
    virtual int getPriorityClass() const;
    virtual void setPriorityClass(int priorityClass);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const simpleMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, simpleMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SIMPLEMSG_M_H

