//
// Generated file, do not edit! Created by nedtool 5.4 from transactionSendMsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __TRANSACTIONSENDMSG_M_H
#define __TRANSACTIONSENDMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include <vector>
#include <map>
typedef std::vector<int> IntVector;
typedef std::vector<double> DoubleVector;
typedef std::map<int, double> IntMap;
// }}

/**
 * Class generated from <tt>transactionSendMsg.msg:29</tt> by nedtool.
 * <pre>
 * packet transactionSendMsg
 * {
 *     int pathIndex;
 *     IntVector transactionPath;
 *     int receiver;
 * 
 * }
 * </pre>
 */
class transactionSendMsg : public ::omnetpp::cPacket
{
  protected:
    int pathIndex;
    IntVector transactionPath;
    int receiver;

  private:
    void copy(const transactionSendMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const transactionSendMsg&);

  public:
    transactionSendMsg(const char *name=nullptr, short kind=0);
    transactionSendMsg(const transactionSendMsg& other);
    virtual ~transactionSendMsg();
    transactionSendMsg& operator=(const transactionSendMsg& other);
    virtual transactionSendMsg *dup() const override {return new transactionSendMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPathIndex() const;
    virtual void setPathIndex(int pathIndex);
    virtual IntVector& getTransactionPath();
    virtual const IntVector& getTransactionPath() const {return const_cast<transactionSendMsg*>(this)->getTransactionPath();}
    virtual void setTransactionPath(const IntVector& transactionPath);
    virtual int getReceiver() const;
    virtual void setReceiver(int receiver);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const transactionSendMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, transactionSendMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TRANSACTIONSENDMSG_M_H

