//
// Generated file, do not edit! Created by nedtool 5.4 from updateMsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __UPDATEMSG_M_H
#define __UPDATEMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>updateMsg.msg:17</tt> by nedtool.
 * <pre>
 * packet updateMsg
 * {
 *     double amount;
 *     int transactionId; //is messageID of transactionMsg
 * }
 * </pre>
 */
class updateMsg : public ::omnetpp::cPacket
{
  protected:
    double amount;
    int transactionId;

  private:
    void copy(const updateMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const updateMsg&);

  public:
    updateMsg(const char *name=nullptr, short kind=0);
    updateMsg(const updateMsg& other);
    virtual ~updateMsg();
    updateMsg& operator=(const updateMsg& other);
    virtual updateMsg *dup() const override {return new updateMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getAmount() const;
    virtual void setAmount(double amount);
    virtual int getTransactionId() const;
    virtual void setTransactionId(int transactionId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const updateMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, updateMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __UPDATEMSG_M_H

